build:
  environment:
    php: 8.1
    variables:
      XDEBUG_MODE: 'coverage'
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests: true
    coverage:
      tests:
        override:
          -
            command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
            coverage:
              file: 'coverage.clover'
              format: 'clover'

filter:
  paths:
    - 'src/*'
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'

checks:
  php: true

tools:
  php_cs_fixer: true
